common_spanish_words = [
    {"spanish": "de", "english": "of, from"},
    {"spanish": "la", "english": "the (feminine)"},
    {"spanish": "que", "english": "that, which"},
    {"spanish": "el", "english": "the (masculine)"},
    {"spanish": "en", "english": "in, on"},
    {"spanish": "y", "english": "and"},
    {"spanish": "a", "english": "to, at"},
    {"spanish": "los", "english": "the (plural masculine)"},
    {"spanish": "se", "english": "himself, herself, itself, themselves"},
    {"spanish": "del", "english": "of the, from the"},
    {"spanish": "las", "english": "the (plural feminine)"},
    {"spanish": "un", "english": "a, an (masculine)"},
    {"spanish": "por", "english": "by, through, for"},
    {"spanish": "con", "english": "with"},
    {"spanish": "no", "english": "no, not"},
    {"spanish": "una", "english": "a, an (feminine)"},
    {"spanish": "su", "english": "his, her, their, your"},
    {"spanish": "para", "english": "for, to, in order to"},
    {"spanish": "es", "english": "is"},
    {"spanish": "al", "english": "to the"},
    {"spanish": "lo", "english": "it, him (masculine direct object pronoun)"},
    {"spanish": "como", "english": "like, as"},
    {"spanish": "más", "english": "more"},
    {"spanish": "pero", "english": "but"},
    {"spanish": "sus", "english": "his, her, its, their (plural)"},
    {"spanish": "le", "english": "to him, to her"},
    {"spanish": "ya", "english": "already, now"},
    {"spanish": "o", "english": "or"},
    {"spanish": "este", "english": "this (masculine)"},
    {"spanish": "sí", "english": "yes"},
    {"spanish": "porque", "english": "because"},
    {"spanish": "esta", "english": "this (feminine)"},
    {"spanish": "entre", "english": "between, among"},
    {"spanish": "cuando", "english": "when"},
    {"spanish": "muy", "english": "very"},
    {"spanish": "sin", "english": "without"},
    {"spanish": "sobre", "english": "on, about, over"},
    {"spanish": "también", "english": "also, too"},
    {"spanish": "me", "english": "me"},
    {"spanish": "hasta", "english": "until, up to, even"},
    {"spanish": "hay", "english": "there is, there are"},
    {"spanish": "donde", "english": "where"},
    {"spanish": "quien", "english": "who"},
    {"spanish": "desde", "english": "from, since"},
    {"spanish": "todo", "english": "everything, all"},
    {"spanish": "nos", "english": "us"},
    {"spanish": "durante", "english": "during"},
    {"spanish": "todos", "english": "all, everyone (masculine)"},
    {"spanish": "uno", "english": "one"},
    {"spanish": "les", "english": "to them, to you (plural)"},
    {"spanish": "ni", "english": "neither, nor"},
    {"spanish": "contra", "english": "against"},
    {"spanish": "otros", "english": "others"},
    {"spanish": "ese", "english": "that (masculine)"},
    {"spanish": "eso", "english": "that (neuter)"},
    {"spanish": "ante", "english": "before, in front of"},
    {"spanish": "ellos", "english": "they (masculine)"},
    {"spanish": "e", "english": "and (before words starting with 'i' or 'hi')"},
    {"spanish": "esto", "english": "this (neuter)"},
    {"spanish": "mí", "english": "me, myself"},
    {"spanish": "ya", "english": "already, yet"},
    {"spanish": "él", "english": "he, him"},
    {"spanish": "tanto", "english": "so much, as much"},
    {"spanish": "esa", "english": "that (feminine)"},
    {"spanish": "estos", "english": "these (masculine)"},
    {"spanish": "mucho", "english": "much, a lot"},
    {"spanish": "quienes", "english": "who (plural)"},
    {"spanish": "nada", "english": "nothing"},
    {"spanish": "muchos", "english": "many"},
    {"spanish": "cual", "english": "which"},
    {"spanish": "poco", "english": "little, few"},
    {"spanish": "ella", "english": "she, her"},
    {"spanish": "estar", "english": "to be (temporary)"},
    {"spanish": "haber", "english": "to have (auxiliary)"},
    {"spanish": "él", "english": "he"},
    {"spanish": "tiene", "english": "has"},
    {"spanish": "nosotros", "english": "we (masculine or mixed)"},
    {"spanish": "vosotros", "english": "you all (informal, masculine)"},
    {"spanish": "ellos", "english": "they"},
    {"spanish": "hacer", "english": "to do, to make"},
    {"spanish": "ir", "english": "to go"},
    {"spanish": "decir", "english": "to say, to tell"},
    {"spanish": "ver", "english": "to see"},
    {"spanish": "dar", "english": "to give"},
    {"spanish": "saber", "english": "to know (facts, info)"},
    {"spanish": "querer", "english": "to want, to love"},
    {"spanish": "llegar", "english": "to arrive"},
    {"spanish": "pasar", "english": "to pass, to happen"},
    {"spanish": "deber", "english": "should, must, to owe"},
    {"spanish": "poner", "english": "to put, to place"},
    {"spanish": "parecer", "english": "to seem, to appear"},
    {"spanish": "quedar", "english": "to stay, to remain"},
    {"spanish": "creer", "english": "to believe"},
    {"spanish": "hablar", "english": "to speak"},
    {"spanish": "llevar", "english": "to carry, to wear"},
    {"spanish": "dejar", "english": "to leave, to let"},
    {"spanish": "seguir", "english": "to follow"},
    {"spanish": "encontrar", "english": "to find"},
    {"spanish": "llamar", "english": "to call"},
    {"spanish": "venir", "english": "to come"},
    {"spanish": "pensar", "english": "to think"},
    {"spanish": "salir", "english": "to leave, to go out"},
    {"spanish": "volver", "english": "to return"},
    {"spanish": "tomar", "english": "to take, to drink"},
    {"spanish": "conocer", "english": "to know (people, places)"},
    {"spanish": "vivir", "english": "to live"},
    {"spanish": "sentir", "english": "to feel"},
]