[project]
name = "machine-learning"
version = "0.1.0"
description = "Beginner Scikit-learn project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.0",
]
